### ISSUE TITLE
 project60.coda Call to undefined method CRM_Core_OptionGroup::getValue() 

### ISSUE THREAD

**Issue by CNCD111111** [Project60/org.project60.coda#11]
bonjour suite à une migration de drupal7 vers drupal10 && php7.4 vers php8.2 j'ai ce message d'erreur lorsque j'essaie d'installer l’extension project60.coda Call to undefined method CRM_Core_OptionGroup::getValue() .
merci d'avance

```
Error: Call to undefined method CRM_Core_OptionGroup::getValue() in /var/www/html/drupal/sites/default/files/civicrm/ext/org.project60.coda/coda.php on line 52 #0 /var/www/html/drupal/vendor/civicrm/civicrm-core/CRM/Extension/Manager/Module.php(70): coda_civicrm_install()
#1 /var/www/html/drupal/vendor/civicrm/civicrm-core/CRM/Extension/Manager/Module.php(38): CRM_Extension_Manager_Module->callHook()
#2 /var/www/html/drupal/vendor/civicrm/civicrm-core/CRM/Extension/Manager.php(296): CRM_Extension_Manager_Module->onPreInstall()
#3 /var/www/html/drupal/vendor/civicrm/civicrm-core/api/v3/Extension.php(42): CRM_Extension_Manager->install()
#4 /var/www/html/drupal/vendor/civicrm/civicrm-core/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_extension_install()
#5 /var/www/html/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(156): Civi\API\Provider\MagicFunctionProvider->invoke()
#6 /var/www/html/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(79): Civi\API\Kernel->runRequest()
#7 /var/www/html/drupal/vendor/civicrm/civicrm-core/api/api.php(28): Civi\API\Kernel->runSafe()
#8 phar:///usr/local/bin/cv/src/Command/BaseCommand.php(63): civicrm_api()
#9 phar:///usr/local/bin/cv/src/Command/ExtensionEnableCommand.php(90): Civi\Cv\Command\BaseCommand->callApiSuccess()
#10 phar:///usr/local/bin/cv/vendor/symfony/console/Command/Command.php(255): Civi\Cv\Command\ExtensionEnableCommand->execute()
#11 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#12 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#13 phar:///usr/local/bin/cv/src/Application.php(59): Symfony\Component\Console\Application->doRun()
#14 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(149): Civi\Cv\Application->doRun()
#15 phar:///usr/local/bin/cv/src/Application.php(26): Symfony\Component\Console\Application->run()
#16 phar:///usr/local/bin/cv/bin/cv(27): Civi\Cv\Application::main()
#17 /usr/local/bin/cv(14): require('...')
#18 {main}
Error: Call to undefined method CRM_Core_OptionGroup::getValue() in coda_civicrm_install() (line 52 of /var/www/html/drupal/sites/default/files/civicrm/ext/org.project60.coda/coda.php).
```

**Comment by bjendres** [comment]
You're right, that extension is not compatible. I'll see if we can fix that....

**Comment by bjendres** [comment]
@CNCD111111  Could you check if https://github.com/Project60/org.project60.coda/tree/issue/11-civicrm-compatibility works for you?

**Comment by CNCD111111** [comment]
thanks

**Comment by bjendres** [comment]
> thanks

Does that mean that it woks and I can create a release?

**Comment by CNCD111111** [comment]
Hi,

Yes, it works

Merci
Nabil H

De : Björn Endres ***@***.***>
Envoyé : mardi 5 mars 2024 11:19
À : Project60/org.project60.coda ***@***.***>
Cc : Nabil Houdeir ***@***.***>; Mention ***@***.***>
Objet : Re: [Project60/org.project60.coda] project60.coda Call to undefined method CRM_Core_OptionGroup::getValue() (Issue #11)

Vous ne recevez pas souvent de courriers de la part de ***@***.******@***.***>. Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

thanks

Does that mean that it woks and I can create a release?

-
